services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=chatbot_rag_spring_ai_db'
      - 'POSTGRES_PASSWORD=Mychatbot@123'
      - 'POSTGRES_USER=spring-ai'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
